In [ ]:
!pip install preprocessing mathutils

In [5]:
import numpy as np
import math
import matplotlib.pyplot as plt
import seaborn as sns
from pylab import rcParams

from preprocessing import *
from mathutils import *

%matplotlib inline

sns.set(style = "whitegrid")

rcParams["figure.figsize"] = 12, 6

random_seed = 42

np.random.seed(random_seed)

In [6]:
def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()
softmax(np.array([[2, 4, 6, 8]]))

array([[0.00214401, 0.0158422 , 0.11705891, 0.86495488]])

Code for XOR function

In [7]:
epochs = 60000
# Layer sizes
inputLayer, hiddenLayer, outputLayer = 2, 3, 1
# Learning rate
LR = 0.1 

In [8]:
# Data
x = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([ [0],   [1],   [1],   [0]])

In [11]:
# Initializing weights to random numbers
w_hidden = np.random.uniform(size=(inputLayer, hiddenLayer))
w_output = np.random.uniform(size=(hiddenLayer,outputLayer))

print(w_hidden)
w_output

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]


array([[0.05808361],
       [0.86617615],
       [0.60111501]])

In [12]:
# Activation FUnction
def sigmoid (x): 
  return 1/(1 + np.exp(-x))

# Derivative of Sigmoid
def sigmoid_prime(x): 
  return x * (1 - x)

In [14]:
for epoch in range(epochs):

  # Forward 
  # Dot product
  act_hidden = sigmoid(np.dot(x, w_hidden))
  output = np.dot(act_hidden, w_output)

  # Caluculate the error
  error = y - output

  if epoch % 5000 == 0:
    print(f"error sum {sum(error)}")

  # Back Prop
  dZ = error * LR
  w_output += act_hidden.T.dot(dZ)
  dH = dZ.dot(w_output.T) * sigmoid_prime(act_hidden)
  w_hidden += x.T.dot(dH)

error sum [-1.77496016]
error sum [0.02481767]
error sum [0.01544889]
error sum [0.01214582]
error sum [0.01032507]
error sum [0.00913186]
error sum [0.00827274]
error sum [0.00761624]
error sum [0.00709348]
error sum [0.00666447]
error sum [0.00630417]
error sum [0.00599601]


In [19]:
test = x[1]

act_hidden = sigmoid(np.dot(test, w_hidden))
np.round(np.dot(act_hidden, w_output))

array([1.])